<?php
/**
 * kreXX: Krumo eXXtended
 *
 * kreXX is a debugging tool, which displays structured information
 * about any PHP object. It is a nice replacement for print_r() or var_dump()
 * which are used by a lot of PHP developers.
 *
 * kreXX is a fork of Krumo, which was originally written by:
 * Kaloyan K. Tsvetkov <kaloyan@kaloyan.info>
 *
 * @author
 *   brainworXX GmbH <info@brainworxx.de>
 *
 * @license
 *   http://opensource.org/licenses/LGPL-2.1
 *
 *   GNU Lesser General Public License Version 2.1
 *
 *   kreXX Copyright (C) 2014-2017 Brainworxx GmbH
 *
 *   This library is free software; you can redistribute it and/or modify it
 *   under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or (at
 *   your option) any later version.
 *   This library is distributed in the hope that it will be useful, but WITHOUT
 *   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *   FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 *   for more details.
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with this library; if not, write to the Free Software Foundation,
 *   Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
?>
<div class="section-config">
    <div class="entry-edit form-inline">
        <div id="krexx-usagehelp-section" class="section-config">
            <div class="entry-edit-head admin__collapsible-block">
                <span id="krexx-usagehelp-link" class="entry-edit-head-link"></span>
                <a id="krexx-usagehelp-head" href="#">Usage help</a>
            </div>
            <fieldset class="config admin__collapsible-block"
                      id="krexx-usagehelp">
                <div class="row">
                    <div class="col-m-12">
                        kreXX will be called in the PHP source code:
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
                            <code>krexx($myObject);</code>
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        Most of the time you will use this method. kreXX will
                        analyse the $object and give you detailed information
                        about it:
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12 rule-tree-wrapper">
                        <div class="rule-tree">
                            <ul>
                                <li>Public attributes of the object</li>
                                <li>Protected attributes of the object (can be
                                    toggled)
                                </li>
                                <li>Private attributes of the object (can be
                                    toggled)
                                </li>
                                <li>Content of the traversable part of the
                                    object (can be toggled)
                                </li>
                                <li>Result of all configured debugging callbacks
                                    (can be configured)
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        In case the variable is not an object, it will simply
                        display its content.
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        <hr/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        Define a "moment" during a benchmark test. The $string
                        should be something meaningful, like "Model invoice db
                        call":
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
                            <code>\Krexx::timerMoment($string);</code>
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        End the benchmark test and displays the result:
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
                            <code>\Krexx::timerEnd();</code>
                        </span><br/><br/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        <hr/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        Outputs backtrace with sourcecode. When kreXX finds
                        objects inside the backtrace, it will analyse them:
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        &nbsp;
                    </div>
                </div>
                <div class="row">
                    <div class="col-m-12">
                        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
                            <code>\Krexx::backtrace();</code>
                        </span>
                    </div>
                </div>
            </fieldset>
            <script type="text/javascript">
                //<![CDATA[
                require(['jquery'], function ($) {
                    var $linkHead = $('#krexx-usagehelp-head');
                    var $linkPayload = $('#krexx-usagehelp');
                    var $linkSection = $('#krexx-usagehelp-section');

                    $linkHead.on('click', function () {
                        $linkPayload.toggle();
                        $linkSection.toggleClass('active');
                    })
                });
                //]]>
            </script>
        </div>
    </div>
</div>