<?php
/**
 * kreXX: Krumo eXXtended
 *
 * kreXX is a debugging tool, which displays structured information
 * about any PHP object. It is a nice replacement for print_r() or var_dump()
 * which are used by a lot of PHP developers.
 *
 * kreXX is a fork of Krumo, which was originally written by:
 * Kaloyan K. Tsvetkov <kaloyan@kaloyan.info>
 *
 * @author
 *   brainworXX GmbH <info@brainworxx.de>
 *
 * @license
 *   http://opensource.org/licenses/LGPL-2.1
 *
 *   GNU Lesser General Public License Version 2.1
 *
 *   kreXX Copyright (C) 2014-2017 Brainworxx GmbH
 *
 *   This library is free software; you can redistribute it and/or modify it
 *   under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or (at
 *   your option) any later version.
 *   This library is distributed in the hope that it will be useful, but WITHOUT
 *   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *   FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 *   for more details.
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with this library; if not, write to the Free Software Foundation,
 *   Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
?>
<main class="page-content">
    <h2>Usage</h2>
    <p>
        kreXX will be called in the PHP source code:<br/><br/>
        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
            <code>krexx($myObject);</code>
        </span><br/><br/>
    </p>
    <p>
        Most of the time you will use this method. kreXX will analyse the
        $object
        and give you detailed information about it:
    </p>

    <ul>
        <li>Public attributes of the object</li>
        <li>Protected attributes of the object (can be toggled)</li>
        <li>Private attributes of the object (can be toggled)</li>
        <li>Content of the traversable part of the object (can be toggled)</li>
        <li>Result of all configured debugging callbacks (can be configured)
        </li>
    </ul>

    <p>
        In case the variable is not an object, it will simply display its
        content.
    </p>

    <br/><hr/><br/>

    <p>
        Define a "moment" during a benchmark test. The $string should be
        something meaningful, like "Model invoice db call":<br/><br/>
        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
            <code>\Krexx::timerMoment($string);</code>
        </span><br/><br/>
    </p>



    <p>
        End the benchmark test and displays the result:<br/><br/>
        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
            <code>\Krexx::timerEnd();</code>
        </span><br/><br/>
    </p>

    <br/><hr/><br/>

    <p>
        Outputs backtrace with sourcecode. When kreXX finds objects inside the
        backtrace, it will analyse them:<br/><br/>
        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
            <code>\Krexx::backtrace();</code>
        </span><br/><br/>
    </p>

    <br/><hr/><br/>

    <p>
        Register the fatal error handler in the system, works only with PHP 5.x:<br/><br/>
        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
            <code>\Krexx::registerFatal();</code>
        </span><br/><br/>
    </p>

    <p>
        Unregister the fatal error handler in the system, works only with PHP 5.x:<br/><br/>
        <span style="background-color: #efefef; border: 1px solid #d8d8d8; margin: -1px 0 0; padding: 10px 10px 10px 26px;">
            <code>\Krexx::unregisterFatal();</code>
        </span><br/><br/>
    </p>

    <br/><hr/><br/>

    <h2>kreXX on the web</h2>
    <p>
        <a target="_blank" href="https://docs.typo3.org/typo3cms/extensions/includekrexx/">Documentation</a><br/>
        <a target="_blank" href="https://github.com/brainworxx/kreXX/issues">Bug reports for kreXX</a><br/>
        <a target="_blank" href="https://github.com/brainworxx/kreXX-Magento-1-Extension/issues">Bug reports for the Magento 1 kreXX extension</a><br/>
        <a target="_blank" href="https://typo3.org/extensions/repository/view/includekrexx">TYPO3 kreXX</a><br/>
        <a target="_blank" href="https://www.magentocommerce.com/magento-connect/krexx-debugger.html">Magento 1 kreXX</a>
    </p>


</main>
