<?php
/**
 * kreXX: Krumo eXXtended
 *
 * kreXX is a debugging tool, which displays structured information
 * about any PHP object. It is a nice replacement for print_r() or var_dump()
 * which are used by a lot of PHP developers.
 *
 * kreXX is a fork of Krumo, which was originally written by:
 * Kaloyan K. Tsvetkov <kaloyan@kaloyan.info>
 *
 * @author
 *   brainworXX GmbH <info@brainworxx.de>
 *
 * @license
 *   http://opensource.org/licenses/LGPL-2.1
 *
 *   GNU Lesser General Public License Version 2.1
 *
 *   kreXX Copyright (C) 2014-2017 Brainworxx GmbH
 *
 *   This library is free software; you can redistribute it and/or modify it
 *   under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or (at
 *   your option) any later version.
 *   This library is distributed in the hope that it will be useful, but WITHOUT
 *   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *   FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 *   for more details.
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with this library; if not, write to the Free Software Foundation,
 *   Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

\Krexx::editSettings();
?>
<?php if (\Krexx::$pool->config->getSetting('disabled')) { ?>

    <div class="row">
        <div class="col-m-12">
            Normally, we would display the menu for the local browser settings here.
        </div>
    </div>
    <div class="row">
        <div class="col-m-12">
            The output of kreXX was <b>disabled</b>, so it will not be displayed.
        </div>
    </div>

<?php } else { ?>
    <?php if (\Krexx::$pool->config->getSetting('destination') == 'file') { ?>
        <div class="row">
            <div class="col-m-12">
                Normally, we would display the menu for the local browser settings here.
            </div>
        </div>
        <div class="row">
            <div class="col-m-12">
                The output of kreXX is switched to <b>file</b>, so it will not be displayed.
            </div>
        </div>
        <div class="row">
            <div class="col-m-12">
                The logfile access can be found <a href="<?php echo $this->getUrl('m2krexx/logging/index') ?>">here</a>.
            </div>
        </div>


    <?php } else { ?>

        <div class="row">
            <div class="col-m-12">
                Here you can edit the local browser settings. They are stored in a cookie, and only affect your current browser. Unlike the configuration file, not all settings can be edited here by default.
            </div>
        </div>
        <div class="row">
            <div class="col-m-12">
                This can be changed <a href="<?php echo $this->getUrl('m2krexx/config/fe') ?>">here</a>. Local browser settings overwrite configuration file settings.
            </div>
        </div>
        <br/><br/>
        <b>Please note, that these settings only affect your current browser!</b>
    <?php } ?>
<?php } ?>
<br /><br /><br /><br /><br /><br />
<hr />

<div class="accordion">
    <?php echo $this->getChildHtml('m2krexx_help_usage') ?>
    <?php echo $this->getChildHtml('m2krexx_help_config') ?>
    <?php echo $this->getChildHtml('m2krexx_help_links') ?>
</div>
