<?php
/**
 * kreXX: Krumo eXXtended
 *
 * kreXX is a debugging tool, which displays structured information
 * about any PHP object. It is a nice replacement for print_r() or var_dump()
 * which are used by a lot of PHP developers.
 *
 * kreXX is a fork of Krumo, which was originally written by:
 * Kaloyan K. Tsvetkov <kaloyan@kaloyan.info>
 *
 * @author
 *   brainworXX GmbH <info@brainworxx.de>
 *
 * @license
 *   http://opensource.org/licenses/LGPL-2.1
 *
 *   GNU Lesser General Public License Version 2.1
 *
 *   kreXX Copyright (C) 2014-2017 Brainworxx GmbH
 *
 *   This library is free software; you can redistribute it and/or modify it
 *   under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation; either version 2.1 of the License, or (at
 *   your option) any later version.
 *   This library is distributed in the hope that it will be useful, but WITHOUT
 *   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 *   FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
 *   for more details.
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with this library; if not, write to the Free Software Foundation,
 *   Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */
?>
<form id="m2krexx_fe" action="<?php echo $this->getUrl('m2krexx/config/savefe') ?>" method="post" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey') ?>
    <h3>Here you can edit the frontend configuration form.</h3>
    <table border="0">
        <tr>
            <td><?php echo __('full edit'); ?></td>
            <td>&nbsp;<?php echo __('= The value can be edited in the frontend.'); ?></td>
        </tr>
        <tr>
            <td>display</td>
            <td>&nbsp;<?php echo __('= The value will only be displayed. kreXX will not accept any values for this setting.'); ?></td>
        </tr>
        <tr>
            <td>do not display</td>
            <td>&nbsp;<?php echo __('= kreXX will not display the value, nor accept any values for this setting.'); ?></td>
        </tr>
    </table>

    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <h3><?php echo __('Output'); ?></h3>
        <table class="data-grid">
            <thead>
            <tr>
                <th class="data-grid-th kleft"><?php echo __('Description'); ?></th>
                <th class="data-grid-th"><?php echo __('Setting'); ?></th>
                <th class="data-grid-th kright"><?php echo __('Use factory settings'); ?></th>
            </tr>
            </thead>

            <tbody>
            <tr class="even">
                <td><span><?php echo __('Disable output:'); ?></span></td>
                <td>
                    <select name="output[disabled]" id="disabled" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['output']['disabled']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="disabled"></label>
                </td>
                <td>
                    <input id="factory.disabled" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['disabled']; ?>/>
                    <label for="factory.disabled"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('IP Range:'); ?></span></td>
                <td><span><?php echo __('This setting is not editable on the frontend.'); ?></span></td>
                <td></td>
            </tr>
            <tr class="even">
                <td><span><?php echo __('Skin'); ?></span></td>
                <td>
                    <select name="output[skin]" id="skin" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['output']['skin']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="skin"></label>
                </td>
                <td>
                    <input id="factory.skin" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['skin']; ?>/>
                    <label for="factory.skin"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('Destination:'); ?></span></td>
                <td><span><?php echo __('This setting is not editable on the frontend.'); ?></span></td>
                <td></td>
            </tr>
            <tr class="even">
                <td><span><?php echo __('Maximum files in the logfolder:'); ?></span></td>
                <td><span><?php echo __('This setting is not editable on the frontend.'); ?></span></td>
                <td></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <h3><?php echo __('Runtime'); ?></h3>
        <table class="data-grid">
            <thead>
            <tr>
                <th class="data-grid-th kleft"><?php echo __('Description'); ?></th>
                <th class="data-grid-th"><?php echo __('Setting'); ?></th>
                <th class="data-grid-th kright"><?php echo __('Use factory settings'); ?></th>
            </tr>
            </thead>

            <tbody>
            <tr class="even">
                <td><span><?php echo __('Try to detect AJAX requests:'); ?></span></td>
                <td>
                    <select name="runtime[detectAjax]" id="detectAjax" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['runtime']['detectAjax']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="detectAjax"></label>
                </td>
                <td>
                    <input id="factory.detectAjax" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['detectAjax']; ?>/>
                    <label for="factory.detectAjax"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('Maximum nesting level for objects and arrays:'); ?></span></td>
                <td>
                    <select name="runtime[level]" id="level" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['runtime']['level']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="level"></label>
                </td>
                <td>
                    <input id="factory.level" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['level']; ?>/>
                    <label for="factory.level"></label>
                </td>
            </tr>
            <tr class="even">
                <td><span><?php echo __('Maximum amount of calls:'); ?></span></td>
                <td>
                    <select name="runtime[maxCall]" id="maxCall" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['runtime']['maxCall']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="maxCall"></label>
                </td>
                <td>
                    <input id="factory.maxCall" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['maxCall']; ?>/>
                    <label for="factory.maxCall"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('Minimum amout of memory [MB]:'); ?></span></td>
                <td>
                    <select name="runtime[memoryLeft]" id="memoryLeft" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['runtime']['memoryLeft']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            }
                            ?>
                            <option
                                value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="memoryLeft"></label>
                </td>
                <td>
                    <input id="factory.memoryLeft" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['memoryLeft']; ?>/>
                    <label for="factory.memoryLeft"></label>
                </td>
            </tr>
            <tr class="even">
                <td><span><?php echo __('Maximum Runtime [Seconds]:'); ?></span></td>
                <td>
                    <select name="runtime[maxRuntime]" id="maxRuntime" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['runtime']['maxRuntime']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="maxRuntime"></label>
                </td>
                <td>
                    <input id="factory.maxRuntime" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['maxRuntime']; ?>/>
                    <label for="factory.maxRuntime"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('Use scope analysis:'); ?></span></td>
                <td>
                    <select name="runtime[useScopeAnalysis]" id="useScopeAnalysis" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['runtime']['useScopeAnalysis']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            }
                            ?>
                            <option
                                value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="useScopeAnalysis"></label>
                </td>
                <td>
                    <input id="factory.useScopeAnalysis" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['useScopeAnalysis']; ?>/>
                    <label for="factory.useScopeAnalysis"></label>
                </td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <h3><?php echo __('Properties'); ?></h3>
        <table class="data-grid">
            <thead>
            <tr>
                <th class="data-grid-th kleft"><?php echo __('Description'); ?></th>
                <th class="data-grid-th"><?php echo __('Setting'); ?></th>
                <th class="data-grid-th kright"><?php echo __('Use factory settings'); ?></th>
            </tr>
            </thead>
            <tbody>
            <tr class="even">
                <td><span><?php echo __('Analyse protected properties:'); ?></span></td>
                <td>
                    <select name="properties[analyseProtected]" id="analyseProtected" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['properties']['analyseProtected']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="analyseProtected"></label>
                </td>
                <td>
                    <input id="factory.analyseProtected" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analyseProtected']; ?>/>
                    <label for="factory.analyseProtected"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('Analyse private properties:'); ?></span></td>
                <td>
                    <select name="properties[analysePrivate]" id="analysePrivate" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['properties']['analysePrivate']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="analysePrivate"></label>
                </td>
                <td>
                    <input id="factory.analysePrivate" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analysePrivate']; ?>/>
                    <label for="factory.analysePrivate"></label>
                </td>
            </tr>
            <tr class="even">
                <td><span><?php echo __('Analyse constants:'); ?></span></td>
                <td>
                    <select name="properties[analyseConstants]" id="analyseConstants" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['properties']['analyseConstants']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="analyseConstants"></label>
                </td>
                <td>
                    <input id="factory.analyseConstants" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analyseConstants']; ?>/>
                    <label for="factory.analyseConstants"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('Analyse traversable data:'); ?></span></td>
                <td>
                    <select name="properties[analyseTraversable]" id="analyseTraversable" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['properties']['analyseTraversable']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="analyseTraversable"></label>
                </td>
                <td>
                    <input id="factory.analyseTraversable" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analyseTraversable']; ?>/>
                    <label for="factory.analyseTraversable"></label>
                </td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <h3><?php echo __('Methods'); ?></h3>
        <table class="data-grid">
            <thead>
            <tr>
                <th class="data-grid-th kleft"><?php echo __('Description'); ?></th>
                <th class="data-grid-th"><?php echo __('Setting'); ?></th>
                <th class="data-grid-th kright"><?php echo __('Use factory settings'); ?></th>
            </tr>
            </thead>
            <tbody>
            <tr class="even">
                <td><span><?php echo __('Analyse protected class methods:'); ?></span></td>
                <td>
                    <select name="methods[analyseProtectedMethods]" id="analyseProtectedMethods" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['methods']['analyseProtectedMethods']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="analyseProtectedMethods"></label>
                </td>
                <td>
                    <input id="factory.analyseProtectedMethods" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analyseProtectedMethods']; ?>/>
                    <label for="factory.analyseProtectedMethods"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('Analyse private class methods:'); ?></span></td>
                <td>
                    <select name="methods[analysePrivateMethods]" id="analysePrivateMethods" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['methods']['analysePrivateMethods']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="analysePrivateMethods"></label>
                </td>
                <td>
                    <input id="factory.analysePrivateMethods" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analysePrivateMethods']; ?>/>
                    <label for="factory.analysePrivateMethods"></label>
                </td>
            </tr>
            <tr class="even">
                <td><span><?php echo __('Analyse getter methods:') ?></span></td>
                <td>
                    <select name="methods[analyseGetter]" id="analyseGetter" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['methods']['analyseGetter']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="analyseGetter"></label>
                </td>
                <td>
                    <input id="factory.analyseGetter" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['analyseGetter']; ?>/>
                    <label for="factory.analyseGetter"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('List of debug methods to poll for data:'); ?></span></td>
                <td><span><?php echo __('This setting is not editable on the frontend.'); ?></span></td>
                <td></td>
            </tr>
            </tbody>
        </table>
    </div>

    <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
        <h3><?php echo __('Error Handling and Backtrace'); ?></h3>
        <table class="data-grid">
            <thead>
            <tr>
                <th class="data-grid-th kleft"><?php echo __('Description'); ?></th>
                <th class="data-grid-th"><?php echo __('Setting'); ?></th>
                <th class="data-grid-th kright"><?php echo __('Use factory settings'); ?></th>
            </tr>
            </thead>
            <tbody>
            <tr class="even">
                <td><span><?php echo __('Maximum count of steps in the backtrace:'); ?></span></td>
                <td>
                    <select name="pruneOutput[maxStepNumber]" id="maxStepNumber" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['pruneOutput']['maxStepNumber']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option
                                value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="maxStepNumber"></label>
                </td>
                 <td>
                    <input id="factory.maxStepNumber" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['maxStepNumber']; ?>/>
                    <label for="factory.maxStepNumber"></label>
                </td>
            </tr>
            <tr>
                <td><span><?php echo __('Maximum array size before fallback to simplified analysis:'); ?></span></td>
                <td>
                    <select name="pruneOutput[arrayCountLimit]" id="arrayCountLimit" class="select admin__control-select">
                        <?php foreach ($data['settings'] as $key => $value) {
                            if ($key == $settings['pruneOutput']['arrayCountLimit']) {
                                $selected = 'selected="selected"';
                            } else {
                                $selected = '';
                            } ?>
                            <option
                                value="<?php echo $key; ?>" <?php echo $selected; ?> ><?php echo $value; ?></option>
                        <?php } ?>
                    </select>
                    <label for="arrayCountLimit"></label>
                </td>
                 <td>
                    <input id="factory.arrayCountLimit" class="admin__control-checkbox" type="checkbox" value="1" name="factory" <?php echo $factory['arrayCountLimit']; ?>/>
                    <label for="factory.arrayCountLimit"></label>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</form>



<br /><br /><br /><br /><br /><br />
<hr />

<script type="text/javascript">
    //<![CDATA[

    (function () {
        "use strict";

        var toggle = function (checkbox) {
            var id = checkbox.id.split('.');
            if (id[1] !== 'undefined') {
                var element = document.getElementById(id[1]);
            }

            if (typeof element === 'object' && element !== 'undefined' && element !== null) {
                element.disabled = checkbox.checked;
            }
        };

        var checkboxes = document.getElementsByName('factory');

        for (var i = 0, n = checkboxes.length; i < n; i++) {
            toggle(checkboxes[i]);
            // var checkbox[i] = checkboxes[i]
            checkboxes[i].addEventListener('click', function () {
                toggle(this);
            }, true);
        }



    })();

    // Submit the form above. Is used by the toobyr button
    // @see Brainworxx\M2krexx\Block\Adminhtml\Config\Edit
    // @see _prepareLayout()

    var submitMainform = function() {
        document.getElementById('m2krexx_fe').submit();
    }
    //]]>
</script>

<div class="accordion">
    <?php echo $this->getChildHtml('m2krexx_help_usage') ?>
    <?php echo $this->getChildHtml('m2krexx_help_config') ?>
    <?php echo $this->getChildHtml('m2krexx_help_links') ?>
</div>