<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

// ui-state-active --> active tab call on li


?>
<?php if (!empty($tabs)): ?>

<div class="admin__page-nav" data-role="container" id="<?php /* @escapeNotVerified */ echo $block->getId() ?>">
    <?php if ($block->getTitle()): ?>
        <div class="admin__page-nav-title" data-role="title" <?php /* @escapeNotVerified */ echo $block->getUiId('title') ?>>
            <strong><?php /* @escapeNotVerified */ echo $block->getTitle() ?></strong>
            <span data-role="title-messages" class="admin__page-nav-title-messages"></span>
        </div>
    <?php endif ?>
    <ul <?php /* @escapeNotVerified */ echo $block->getUiId('tab', $block->getId()) ?> class="<?php /* @escapeNotVerified */ echo $block->getIsHoriz() ? 'tabs-horiz' : 'tabs admin__page-nav-items' ?>">
        <?php foreach ($tabs as $_tabName => $_tab): ?>
            <?php if (!$block->canShowTab($_tab)): continue;  endif; ?>
            <?php $_tabClass = 'tab-item-link ' . $block->getTabClass($_tab) ?>
            <li class="admin__page-nav-item <?php if ($block->getActive() === $_tabName) : echo 'ui-state-active'; endif; ?>"
                <?php if ($block->getTabIsHidden($_tab)): ?> style="display:none"<?php endif; ?>
                <?php /* @escapeNotVerified */ echo $block->getUiId('tab', 'item', $_tab->getId()) ?>
            >
                <a href="<?php /* @escapeNotVerified */ echo $block->getTabUrl($_tab) ?>" id="<?php /* @escapeNotVerified */ echo $block->getTabId($_tab) ?>" name="<?php /* @escapeNotVerified */ echo $block->getTabId($_tab, false) ?>" title="<?php /* @escapeNotVerified */ echo $block->getTabTitle($_tab) ?>"
                   class="admin__page-nav-link <?php /* @escapeNotVerified */ echo $_tabClass;?>"
                   <?php /* @escapeNotVerified */ echo $block->getUiId('tab', 'link', $_tab->getId()) ?>>
                   <span><?php /* @escapeNotVerified */ echo $block->getTabLabel($_tab); ?></span>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>